//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.QUANLYKHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaisp_QLK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaisp_QLK()
        {
            this.sanpham_QLK = new HashSet<sanpham_QLK>();
        }
    
        public string Maloai_QLK { get; set; }
        public string Tenloai_QLK { get; set; }
        public Nullable<bool> Hieuluc_QLK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_QLK> sanpham_QLK { get; set; }
    }
}
