//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.QUANLYNHANSU
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMNHANVIEN
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string ChucVu { get; set; }
        public string MADV { get; set; }
        public string EMail { get; set; }
        public Nullable<byte> LapPhieu { get; set; }
        public Nullable<byte> TPB_kiemtra { get; set; }
        public Nullable<byte> XemXet { get; set; }
        public Nullable<byte> PheDuyet { get; set; }
        public Nullable<byte> TiepNhan { get; set; }
        public string Passwordid { get; set; }
        public Nullable<byte> HieuLuc { get; set; }
        public Nullable<byte> KIEMTRA { get; set; }
        public string MABP { get; set; }
        public string IDMaDV { get; set; }
        public Nullable<bool> QuanTri { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public byte[] Chuki { get; set; }
        public Nullable<bool> TinhGTMay { get; set; }
        public Nullable<System.DateTime> NgayHieuLucPass { get; set; }
    }
}
