//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.QUANLYNHANSU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phuongxa_QLNS
    {
        public string Maphuongxa_QLNS { get; set; }
        public string Maquanhuyen_QLNS { get; set; }
        public string Matinhthanh_QLNS { get; set; }
        public string Tenphuongxa_QLNS { get; set; }
    
        public virtual Tinhthanh_QLNS Tinhthanh_QLNS { get; set; }
        public virtual Quanhuyen_QLNS Quanhuyen_QLNS { get; set; }
    }
}
