//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.QUANLYNHANSU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYNHANSUEntities1 : DbContext
    {
        public QUANLYNHANSUEntities1()
            : base("name=QUANLYNHANSUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Phuongxa_QLNS> Phuongxa_QLNS { get; set; }
        public virtual DbSet<Quanhuyen_QLNS> Quanhuyen_QLNS { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tinhthanh_QLNS> Tinhthanh_QLNS { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Page> User_Page { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<DMNHANVIEN> DMNHANVIENs { get; set; }
    }
}
