//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsApp.EntityFramework.QUANLYNHANSU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tinhthanh_QLNS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tinhthanh_QLNS()
        {
            this.Phuongxa_QLNS = new HashSet<Phuongxa_QLNS>();
            this.Quanhuyen_QLNS = new HashSet<Quanhuyen_QLNS>();
        }
    
        public string Matinhthanh_QLNS { get; set; }
        public string Tentinhthanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phuongxa_QLNS> Phuongxa_QLNS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quanhuyen_QLNS> Quanhuyen_QLNS { get; set; }
    }
}
